dictionaries = ["en_us"]
use_global = false

words = [
  "AMPDU",
  "BAUDRATE",
  "bistatic",
  "Caddy",
  "Caddyfile",
  "cmake",
  "codebook",
  "CSI",
  "dasharray",
  "Doptimize",
  "esptool",
  "ESPTOOLPY",
  "Espressif",
  "ESP",
  "fetchurl",
  "Fixup",
  "FLASHSIZE",
  "FreeRTOS",
  "IDF",
  "JTAG",
  "linecap",
  "MCS",
  "metre",
  "mkdir",
  "multipath",
  "ndata",
  "netif",
  "NixOS",
  "nixd",
  "nixpkgs",
  "NOSYSTEM",
  "nums",
  "nvs",
  "pkgs",
  "pname",
  "pyserial",
  "redir",
  "rssi",
  "RTOS",
  "sdkconfig",
  "sed",
  "Segoe",
  "Sparkline",
  "SRCS",
  "stdenv",
  "subcarrier",
  "subcarriers",
  "thekorn",
  "tls",
  "topbar",
  "UART",
  "Xtensa",
  "Zig",
  "zls",
]

ignore_paths = [
  "dependencies.lock",
  "flake.lock",
  "build/**",
  "managed_components/**",
]
